spring.application.name=SpringBootCourse-App1

# db connection
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# logging
spring.main.banner-mode=off
logging.level.root=warn


