spring.application.name=SpringBootCourse-App1

# db connection
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# logging
spring.main.banner-mode=off
logging.level.root=warn

# logging to display sql statements
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace 

# data-rest config
spring.data.rest.base-path=/api
spring.data.rest.default-page-size=20 


# auto create tables w JPA/Hibernate
# create method drops existing tablesnand then creates 
# spring.jpa.hibernate.ddl-auto=create 
# spring.jpa.hibernate.ddl-auto=update


