spring.application.name=SpringBootCourse-App1

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
# management.endpoints.web.exposure.exclude=health

# threaddump actuator: lists all the threads running / useful when analizing performance of the app
info.app.name=first boot app 
info.app.description=learning is a process
info.app.version=0.0.1
